spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/postgres

logging:
  level:
    edu:
      umass:
        orgitect: debug

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus,env,info,flyway
#springdoc:
#  show-actuator: true