
spring:
  application:
    name: stages-service

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    clean-on-validation-error: false
    enabled: true
    mixed: true

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus,env,info,flyway

server:
  port: 8080

springdoc:
  packagesToScan: edu.umass.orgitect.stages_service
  swagger-ui:
    configUrl: http://localhost:8080/v3/api-docs/swagger-config
    url: http://localhost:8080/v3/api-docs